name: Website Deployment
on:
  push:
    branches:
    - master
    paths:
    - 'website/**'

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache/restore dependencies
      uses: actions/cache@v1
      id: cache
      with:
        path: ./website/node_modules
        key: website-${{ hashFiles('website/yarn.lock') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --cwd ./website
    - name: Add ssh keys
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cat <<EOT >> ~/.ssh/config
        Host github.com
        HostName github.com
        IdentityFile ~/.ssh/id_rsa
        EOT
    - name: Release
      working-directory: ./website
      env:
        USE_SSH: true
        GIT_USER: git
      run: |
        git config --global user.email "actions@gihub.com"
        git config --global user.name "gh-actions"
        yarn deploy



